"""Build NotebookLM handoff files for improving the ParkPulse deck.

Outputs:
- reports/notebooklm_deck_context.docx
- reports/notebooklm_prompt.txt
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from docx import Document
from docx.shared import Inches, Pt, RGBColor


ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "outputs" / "tables"
FRONTEND = ROOT / "outputs" / "frontend"
REPORTS = ROOT / "reports"
DOCX_OUT = REPORTS / "notebooklm_deck_context.docx"
PROMPT_OUT = REPORTS / "notebooklm_prompt.txt"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text()) if path.exists() else {}


def pct(value: float) -> str:
    return f"{100 * float(value):.1f}%"


def num(value: float) -> str:
    return f"{float(value):,.0f}"


def add_kv_table(doc: Document, rows: list[tuple[str, str]]) -> None:
    table = doc.add_table(rows=1, cols=2)
    table.style = "Light Grid Accent 1"
    table.rows[0].cells[0].text = "Item"
    table.rows[0].cells[1].text = "Detail"
    for key, value in rows:
        cells = table.add_row().cells
        cells[0].text = key
        cells[1].text = value


def build_prompt(metrics: dict) -> str:
    return f"""You are an expert Product Management + AI/ML strategy deck creator for a national traffic-tech hackathon.

I am uploading two decks and one context document:
1. ParkPulse Bengaluru deck generated by our team.
2. A reference shortlisted Flipkart/HiLabs deck. Do NOT copy its topic, text, or content. Use it only to understand the quality bar: sharp opening question, dense logic boards, clear PM reasoning, quantifiable model proof, trade-offs, implementation plan, and executive storytelling.
3. A Word context document with the full ParkPulse problem, dataset, modelling, metrics, product architecture, limitations, and desired positioning.

Your task:
Create a better max-15-slide deck outline and slide-by-slide content plan for ParkPulse Bengaluru. It must feel like a finalist/winner deck, not a generic analytics report.

Hard requirements:
- Theme: AI-driven parking intelligence to detect illegal parking hotspots and quantify impact on traffic flow for targeted enforcement.
- Positioning: ParkPulse is a deployment engine, not just a dashboard.
- It must combine Product Management and AI/Data Science thinking.
- It must be honest that the current data has violation records, not live speed, queue length, surveyed lane geometry, signal-health, or live workforce feeds.
- It must still show why the solution is day-1 implementable using only the provided enforcement dataset.
- Max 15 slides.
- Every slide must have one clear takeaway.
- Use the reference deck’s style logic: sharp problem question, dense but organized boards, formula boxes, comparison tables, proof panels, scorecards, roadmap and trade-offs.
- The current deck already embeds real dashboard screenshots from the working frontend: Command Center, Hotspot Intelligence, and Deployment Simulator. Improve their story placement rather than treating them as decoration.
- Useful external inspiration reviewed: editable-PPT workflows, frontend-derived slide screenshots, open-design systems, UI/UX critique skills, and PM strategy skills. Do not mention Claude plugins in the final deck unless asked; use the ideas silently as quality standards.
- Use our actual numbers:
  - Total records: {num(metrics.get("total_violations", 0))}
  - Hotspot cells: {num(metrics.get("total_hotspots", 0))}
  - Validated recurrence Capture@20: {pct(metrics.get("headline_recurrence_capture_at_20", 0))}
  - Top-20 ELRM: {num(metrics.get("top20_lane_recovery_minutes", 0))} lane-minutes
  - Chronic repeat priority zones: {num(metrics.get("chronic_repeat_priority_zones", 0))}
  - Patrol-gap priority zones: {num(metrics.get("patrol_gap_priority_zones", 0))}
  - High spillback risk zones: {num(metrics.get("high_spillback_risk_zones", 0))}
  - Median clearance SLA: {num(metrics.get("median_clearance_sla_minutes", 0))} minutes
  - Robust top-20 overlap: {pct(metrics.get("robust_top20_overlap", 0))}

Recommended narrative:
1. Open with: “Which illegal parking should Bengaluru solve first?”
2. Decode the theme and judge criteria.
3. Give a one-page executive strategy board.
4. Show why reactive patrol fails.
5. Show EDA proof: concentration, repeat vehicles, road-space context, exposure bias.
6. Show ParkPulse architecture.
7. Show scoring and modelling: recurrence model, TORI, repeat pressure, patrol gap, ELRM.
8. Show validation and the honest distinction between recurrence prediction and action scoring.
9. Show spatial/corridor intelligence and map story.
10. Show operational payoff and resource plan.
11. Show product experience: command center, live ops brief, hotspot intelligence, simulator, methodology.
12. Show a sample officer field brief.
13. Show implementation roadmap.
14. Show risks/limitations and mitigations.
15. Close with why it wins.

Output format:
- First, give the recommended 15-slide storyline.
- Then give detailed slide content: title, key message, layout, visual elements, exact metrics to include, and speaker note.
- Then list design improvements to apply compared to the current ParkPulse deck.
- Then list what to remove if the deck feels too crowded.
- Do not invent unavailable data. Clearly mark proxies.
"""


def build() -> None:
    REPORTS.mkdir(exist_ok=True)
    metrics = load_json(FRONTEND / "metrics.json")
    strategy = load_json(TABLES / "strategy_validation_summary.json")
    policy = load_json(TABLES / "deployment_policy_summary.json")
    eda = pd.read_csv(TABLES / "theme_signal_summary.csv")
    context = pd.read_csv(TABLES / "theme_signal_context_features.csv")
    plan = pd.read_csv(TABLES / "daily_enforcement_plan.csv")

    doc = Document()
    section = doc.sections[0]
    section.top_margin = Inches(0.55)
    section.bottom_margin = Inches(0.55)
    section.left_margin = Inches(0.65)
    section.right_margin = Inches(0.65)
    styles = doc.styles
    styles["Normal"].font.name = "Aptos"
    styles["Normal"].font.size = Pt(10)
    styles["Title"].font.name = "Aptos Display"
    styles["Title"].font.size = Pt(22)
    styles["Heading 1"].font.color.rgb = RGBColor(40, 116, 240)

    doc.add_heading("NotebookLM Context: ParkPulse Bengaluru Deck", 0)
    doc.add_paragraph(
        "Use this document with the ParkPulse deck and the reference shortlisted deck. "
        "The reference deck is only for quality/style logic, not for copying content."
    )

    doc.add_heading("1. Hackathon Theme", level=1)
    doc.add_paragraph(
        "Theme 1 asks: How can AI-driven parking intelligence detect illegal parking hotspots "
        "and quantify their impact on traffic flow to enable targeted enforcement?"
    )

    doc.add_heading("2. Solution Positioning", level=1)
    doc.add_paragraph(
        "ParkPulse Bengaluru is a deployment engine for illegal-parking enforcement. "
        "It converts historical violation records into a ranked, time-windowed action plan "
        "for police control rooms and station-level officers."
    )

    doc.add_heading("3. Core Metrics", level=1)
    add_kv_table(
        doc,
        [
            ("Total violation records", num(metrics.get("total_violations", 0))),
            ("Hotspot cells", num(metrics.get("total_hotspots", 0))),
            ("Validated recurrence Capture@20", pct(metrics.get("headline_recurrence_capture_at_20", 0))),
            ("Top-20 ELRM", f"{num(metrics.get('top20_lane_recovery_minutes', 0))} lane-minutes"),
            ("Chronic repeat priority zones", num(metrics.get("chronic_repeat_priority_zones", 0))),
            ("Patrol-gap priority zones", num(metrics.get("patrol_gap_priority_zones", 0))),
            ("High spillback risk zones", num(metrics.get("high_spillback_risk_zones", 0))),
            ("Median clearance SLA", f"{num(metrics.get('median_clearance_sla_minutes', 0))} minutes"),
            ("Robust top-20 overlap", pct(metrics.get("robust_top20_overlap", 0))),
        ],
    )

    doc.add_heading("4. What The Data Supports", level=1)
    for row in eda.itertuples():
        doc.add_paragraph(f"{row.signal}: {row.finding}", style=None)

    doc.add_heading("5. Important EDA Signals", level=1)
    for row in context.head(8).itertuples():
        doc.add_paragraph(
            f"{row.context_signal}: {100*row.record_share:.1f}% of records, "
            f"{100*row.weighted_share:.1f}% of weighted obstruction."
        )

    doc.add_heading("6. Modelling And Scoring", level=1)
    doc.add_paragraph(
        f"Headline recurrence signal: {strategy.get('headline_recurrence_signal')}; "
        f"Capture@20: {pct(strategy.get('headline_recurrence_capture_at_20', 0))}."
    )
    doc.add_paragraph(
        "TORI is used as the action and explanation layer, not as the sole recurrence predictor. "
        "It combines density, persistence, time-window pressure, context, severity, obstruction, "
        "validation confidence, exposure adjustment, repeat pressure and patrol gap."
    )
    doc.add_paragraph(
        "ELRM means Equivalent Lane Recovery Minutes. It is a transparent operational proxy, "
        "not measured live travel-time or speed."
    )

    doc.add_heading("7. Product Views", level=1)
    for item in [
        "Command Center: city map and six headline KPIs.",
        "Live Ops Brief: dispatch order, tow/patrol need, repeat/gap escalation triggers.",
        "Hotspot Intelligence: why a selected zone matters and the field action plan.",
        "Deployment Simulator: patrol/tow capacity trade-offs.",
        "Methodology: glossary and proxy boundaries.",
        "Current deck screenshots available in outputs/deck_screenshots/: command_center_crop.png, hotspot_intelligence_crop.png, deployment_simulator_crop.png.",
    ]:
        doc.add_paragraph(item)

    doc.add_heading("8. Top Action Mix", level=1)
    for action, count in plan["recommended_action"].value_counts().items():
        doc.add_paragraph(f"{action}: {count} zones")

    doc.add_heading("9. Policy Simulation", level=1)
    doc.add_paragraph(
        f"Standard budget policy: {policy.get('standard_budget_policy')}; "
        f"standard budget recovery: {num(policy.get('standard_budget_recovery_minutes', 0))} lane-minutes; "
        f"recovery per resource-hour: {policy.get('standard_budget_recovery_per_resource_hour')}."
    )

    doc.add_heading("10. Honest Limitations", level=1)
    for item in [
        "No measured live speed or queue length in the dataset.",
        "No surveyed lane geometry; lane-wise outputs are road-space proxies.",
        "No true before/after enforcement outcome because closure/action timestamps are missing.",
        "Signal-health and live workforce are future integrations, not present fields.",
    ]:
        doc.add_paragraph(item)

    doc.add_heading("11. Desired Deck Style", level=1)
    doc.add_paragraph(
        "Use a finalist-quality PM + AI style: sharp opening question, dense but organized logic boards, "
        "formula boxes, scorecards, comparison matrices, data proof, product flow, implementation roadmap, "
        "and a strong closing. Avoid generic dashboard screenshots and avoid overclaiming unavailable data."
    )

    doc.add_heading("12. Plugin-Inspired Deck Workflow", level=1)
    doc.add_paragraph(
        "We reviewed open-source Claude plugin ideas only as workflow inspiration, not as mandatory dependencies. "
        "The useful ideas were: editable native PowerPoint generation, frontend screenshots as product proof, "
        "design-system consistency, PM-style storyline, and clear defensibility. The final implementation remains "
        "a reproducible local Python + React workflow."
    )

    prompt = build_prompt(metrics)
    doc.add_heading("13. Copy-Paste Prompt For NotebookLM", level=1)
    doc.add_paragraph(prompt)

    doc.save(DOCX_OUT)
    PROMPT_OUT.write_text(prompt, encoding="utf-8")
    print(f"Wrote {DOCX_OUT}")
    print(f"Wrote {PROMPT_OUT}")


if __name__ == "__main__":
    build()
